name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    - uses: actions/cache@preview
      name: Use cache
      id: cache
      with:
        path: ~/local/rubies
        key: ruby-2.6.5
    - uses: clupprich/ruby-build-action@master
      name: set up Ruby 2.6.5
      with:
        ruby-version: 2.6.5
        cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}
    - name: Install fir-cli
      run: gem install fir-cli
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: chmod +x ./gradlew && ./gradlew build
    - name: Upload to fir.im
      run: fir publish app/build/outputs/apk/release/app-release.apk -T ${{ secrets.FIR_TOKEN }}
